// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ST10254164_LukeC_GR2_PROG7311_A2.Data;


#nullable disable

namespace ST10254164_LukeC_GR2_PROG7311_A2.Migrations
{
    [DbContext(typeof(applicationDBContext))]
    [Migration("20250514101222_sqlite.local_migration_894")]
    partial class sqlitelocal_migration_894
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ST10254164_LukeC_GR2_PROG7311_A2.Models.employeeModel", b =>
                {
                    b.Property<int>("employeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("farmerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("employeeID");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("ST10254164_LukeC_GR2_PROG7311_A2.Models.farmerModel", b =>
                {
                    b.Property<int>("farmerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("employeeModelemployeeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("farmerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("productCreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("farmerID");

                    b.HasIndex("employeeModelemployeeID");

                    b.ToTable("farmers");
                });

            modelBuilder.Entity("ST10254164_LukeC_GR2_PROG7311_A2.Models.productModel", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("farmerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("productCreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.ToTable("products");
                });

            modelBuilder.Entity("ST10254164_LukeC_GR2_PROG7311_A2.Models.farmerModel", b =>
                {
                    b.HasOne("ST10254164_LukeC_GR2_PROG7311_A2.Models.employeeModel", null)
                        .WithMany("Product")
                        .HasForeignKey("employeeModelemployeeID");
                });

            modelBuilder.Entity("ST10254164_LukeC_GR2_PROG7311_A2.Models.employeeModel", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
