// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ST10254164_LukeC_GR2_PROG7311_A2.Data;

#nullable disable

namespace ST10254164_LukeC_GR2_PROG7311_A2.Migrations
{
    [DbContext(typeof(applicationDBContext))]
    [Migration("20250515141935_sqlite.local_migration_325")]
    partial class sqlitelocal_migration_325
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ST10254164_LukeC_GR2_PROG7311_A2.Models.employeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "EmpP@ss123",
                            Role = "Employee",
                            Username = "employee01"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "FarmP@ss123",
                            Role = "Farmer",
                            Username = "farmerJohn"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "FarmP@ss456",
                            Role = "Farmer",
                            Username = "farmerJane"
                        });
                });

            modelBuilder.Entity("ST10254164_LukeC_GR2_PROG7311_A2.Models.farmerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactDetails")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Farmers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactDetails = "john@sunnyacres.com, 555-0101",
                            Name = "John's Sunny Acres",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            ContactDetails = "jane@greenfields.org, 555-0202",
                            Name = "Jane's Green Fields",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ST10254164_LukeC_GR2_PROG7311_A2.Models.productModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FarmerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Outdoor",
                            FarmerId = 1,
                            Name = "Solar Panel",
                            ProductionDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AddedDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Poultry",
                            FarmerId = 1,
                            Name = "Free-Range Eggs",
                            ProductionDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AddedDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Bakery",
                            FarmerId = 2,
                            Name = "Artisan Bread",
                            ProductionDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AddedDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Category = "Fruit",
                            FarmerId = 2,
                            Name = "Fresh Strawberries",
                            ProductionDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ST10254164_LukeC_GR2_PROG7311_A2.Models.farmerModel", b =>
                {
                    b.HasOne("ST10254164_LukeC_GR2_PROG7311_A2.Models.employeeModel", "employeeModel")
                        .WithOne("FarmerProfile")
                        .HasForeignKey("ST10254164_LukeC_GR2_PROG7311_A2.Models.farmerModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employeeModel");
                });

            modelBuilder.Entity("ST10254164_LukeC_GR2_PROG7311_A2.Models.productModel", b =>
                {
                    b.HasOne("ST10254164_LukeC_GR2_PROG7311_A2.Models.farmerModel", "Farmer")
                        .WithMany("Products")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("ST10254164_LukeC_GR2_PROG7311_A2.Models.employeeModel", b =>
                {
                    b.Navigation("FarmerProfile");
                });

            modelBuilder.Entity("ST10254164_LukeC_GR2_PROG7311_A2.Models.farmerModel", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
